// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnrealContextMenu
{
    internal sealed partial class Vsix
    {
        public const string Id = "UnrealContextMenu.901f7c98-e3e3-4bd0-b1c3-c97bb3b59b80";
        public const string Name = "UnrealContextMenu";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Henrique Tornelli Duarte";
        public const string Tags = "";
    }
}
