// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnrealContextMenu
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string UnrealContextMenuString = "3691719c-ed82-45ba-b3a8-5959b6dbfae5";
        public static Guid UnrealContextMenu = new Guid(UnrealContextMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommandGroup = 0x0001;
        public const int AddUnrealClass = 0x0100;
    }
}